# relative line numbers
hook global BufCreate .* %[
    add-highlighter buffer/ number-lines -relative -hlcursor
    add-highlighter buffer/ wrap
]

add-highlighter global/ show-matching

# disable clippy
#set-option global ui_options ncurses_assistance=off

# indentation
set-option global tabstop	4
set-option global indentwidth	4

# tabs to spaces
hook global InsertChar \t %{
    exec -draft h@
}

colorscheme gruvbox

# plug.kak
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

# plugins
plug "andreyorst/fzf.kak"

# key mappings
map global normal <c-p> ': fzf-mode<ret>'

# language server
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
}

