#!/bin/bash

WALLPAPER=$(find ~/.config/wallpaper/wallpaper-*.*)
[[ $WALLPAPER =~ .+\/wallpaper\/wallpaper-(.+)\.+ ]]

if [[ -z ${BASH_REMATCH[1]} ]]; then
    cp ~/.config/wallpaper/wallpaper-*.* ~/Pictures/Wallpapers/
else
    echo "Wallpaper already saved"
fi
