#!/bin/bash

WALLPAPER=$(find ~/.config/wallpaper/wallpaper-*.*)
[[ ${WALLPAPER} =~ .+\/wallpaper\/(wallpaper-.+)\.+ ]]
SAVED_WALLPAPER=$(find ~/Pictures/Wallpapers/ -maxdepth 1 -name ${BASH_REMATCH[1]}.*)

if [[ -z ${SAVED_WALLPAPER} ]]; then
    cp ~/.config/wallpaper/wallpaper-*.* ~/Pictures/Wallpapers/
else
    echo "Wallpaper already saved"
fi
