#!/bin/bash

# API parameters
QUERY="landscape"
CATEGORIES=010 # general/anime/people
PURITY=100 # sfw/sketchy/nsfw
MINIMUM_RESOLUTION=1920x1080
RATIOS=16x9
SORTING=random
#COLOURS=000000,333399,424153
SEARCH_PARAMS="q=$QUERY&categories=$CATEGORIES&purity=$PURITY&atLeast=$MINIMUM_RESOLUTION&ratios=$RATIOS&colors=$COLOURS&sorting=$SORTING"

# Remove old wallpaper
rm $HOME/.config/wallpaper/wallpaper-*.*

random_wallpapers=$(curl "https://wallhaven.cc/api/v1/search?$SEARCH_PARAMS" 2>/dev/null)
wallpaper=$(echo $random_wallpapers | jq '.data[0].path' | sed -e 's/^"//' -e 's/"$//')
id=$(echo $random_wallpapers | jq '.data[0].id' | sed -e 's/^"//' -e 's/"$//')
filename=$(basename -- "$wallpaper")
extension="${filename##*.}"
curl $(echo $wallpaper) --output $HOME/.config/wallpaper/wallpaper-$id.$extension

sh $HOME/fehbg.sh
